CREATE TABLE MYMEMBER(
    MEM_ID VARCHAR2(15) NOT NULL, --회원 ID
    MEM_NAME VARCHAR2(30) NOT NULL, --회원 이름
    MEM_PASS VARCHAR2(70) NOT NULL, --Password
    MEM_TEL VARCHAR2(14) NOT NULL, --전화번호
    MEM_ADDR VARCHAR2(70) NOT NULL, --주소
    CONSTRAINT PK_MYMEMBER PRIMARY KEY (MEM_ID)
); 

DROP TABLE MYMEMBER;